---
kind: pipeline
name: build
type: docker

steps:
- name: copy placeholder
  image: peaceiris/hugo
  commands:
  - mkdir public
  - mv index.html public/
  - tar -cvf ${DRONE_BRANCH}.sum.fm.tar public/

- name: upload to blob
  image: plugins/s3
  settings:
    endpoint: https://blob.pfudi.de/
    bucket: drone
    access_key: 
      from_secret: blob_access_key
    secret_key: 
      from_secret: blob_secret_key
    source: ${DRONE_BRANCH}.sum.fm.tar
    target: /
    path_style: true


# Copy the files to a docker volume mounted locally
- name: deploy to mounted volume - prod
  image: eeacms/rsync
  volumes:
  - name: prod_directory
    path: /srv/public
  commands:
    - rsync -azv --delete public/ /srv/public/
  when:
    branch:
    - main

- name: deploy to mounted volume - dev
  image: eeacms/rsync
  volumes:
  - name: test_directory
    path: /srv/public
  commands:
    - rsync -azv --delete public/ /srv/public/
  when:
    branch:
    - dev

# Copy the files to a docker volume mounted locally
volumes:
- name: test_directory
  host:
    path: /usr/share/nginx/html/dev.sum.fm/
- name: prod_directory
  host:
    path: /usr/share/nginx/html/dev.sum.fm/
---
kind: signature
hmac: 765bf63d1cae29d79ddbfd7f4aa5fd27290b9d90625f5eb59fa20a446a48d187

...
