---
kind: pipeline
name: build
type: docker

steps:
- name: build hugo website
  image: peaceiris/hugo
  commands:
  - mkdir public
  - mv index.html public/
  - tar -cvf prod.podcast.menschen.software.tar public/
  

- name: deploy to mounted volume - prod
  image: eeacms/rsync
  volumes:
  - name: prod_directory
    path: /srv/public
  commands:
    - rsync -azv --delete public/ /srv/public/
  when:
    branch:
    - main

- name: deploy to mounted volume - dev
  image: eeacms/rsync
  volumes:
  - name: test_directory
    path: /srv/public
  commands:
    - rsync -azv --delete public/ /srv/public/
  when:
    branch:
    - dev

- name: upload to blob - prod
  image: plugins/s3
  settings:
    endpoint: https://blob.pfudi.de/
    bucket: drone
    access_key: 
      from_secret: blob_access_key
    secret_key: 
      from_secret: blob_secret_key
    source: prod.podcast.menschen.software.tar
    target: /
    path_style: true
  when:
    branch:
    - main

- name: upload to blob - test
  image: plugins/s3
  settings:
    endpoint: https://blob.pfudi.de/
    bucket: drone
    access_key: 
      from_secret: blob_access_key
    secret_key: 
      from_secret: blob_secret_key
    source: test.podcast.menschen.software.tar
    target: /
    path_style: true
  when:
    branch:
    - dev

volumes:
- name: test_directory
  host:
    path: /usr/share/nginx/html/test.podcast.menschen.software

volumes:
- name: prod_directory
  host:
    path: /usr/share/nginx/html/podcast.menschen.software